"""LaTeX table fragments of the Part 3 manuscript from the results cache (#54).

Each writer takes a :class:`~pdes_demo.results_cache.ResultsCache` and
returns a booktabs ``tabular`` fragment for ``\\input``, headed by a
``% GENERATED`` comment naming the script and the cache file so nobody
edits it by hand (bolza-bending's ``control_table.tex`` pattern). Numbers
are formatted the way the notes print them: errors as ``\\sci{6.2}{-8}``
(``\\sci`` is defined in ``paper/main.tex``) with two significant digits,
three when the leading digit is 1; rates with one decimal.
"""

from __future__ import annotations

from math import floor, log10
from pathlib import Path

from .results_cache import ResultsCache

MODE_ORDER = (
    "naive",
    "aware",
    "ablate",
    "widen1",
    "widen2",
    "cell",
    "cell2",
    "bandlimit",
    "sfloor",
)
VARIANT_LABELS = {
    "naive": "naive",
    "aware": "interface-aware",
    "seeds": "seeds",
    "floor": "naive, uniform medium",
    "hyper19": r"seeds, 19-node $\Delta^3$ rows",
    "naive-hyper": r"seeds, naive $\Delta^3$ rows kept",
    "seeds30": "seeds, 30-node degree-4 rows",
    "naive19": "19-node degree-3 rows, no seeds",
}


def sci(x: float | None, sig: int | None = None) -> str:
    r"""``6.2e-8`` as ``\sci{6.2}{-8}``.

    ``sig`` significant digits; by default two, three when the leading digit
    is 1 (where two digits would round hardest), the notes' convention.
    """
    if x is None:
        return "--"
    if x == 0:
        return "$0$"
    exp = floor(log10(abs(x)))
    mant = x / 10**exp
    if abs(round(mant, 1)) >= 10:  # 9.96 rounds up to 10.0: roll the exponent
        exp += 1
        mant /= 10
    if sig is None:
        sig = 3 if abs(round(mant, 1)) < 2 else 2
    return rf"\sci{{{mant:.{sig - 1}f}}}{{{exp}}}"


def rate(r: float | None) -> str:
    return "--" if r is None else f"{r:.1f}"


def rates_cell(records: list[dict]) -> str:
    """``4.0, 4.0, 4.0`` from the rates of a sweep's records (first is None)."""
    return ", ".join(rate(r["rate"]) for r in records if r["rate"] is not None)


def delta_label(width: float | None) -> str:
    if width is None:
        return ""
    return "$0$ (jump)" if width == 0 else f"${width:g}$"


COMPARATOR_LABELS = {
    "widen1": "widened, $h$",
    "widen2": "widened, $2h$",
    "cell": "cell mean, $h$",
    "cell2": "cell mean, $2h$",
    "bandlimit": "band-limited",
}


def mode_label(mode: str, width: float | None, one_d: bool = False) -> str:
    if mode == "naive":
        return "standard FD4" if one_d else "naive"
    if mode == "aware":
        return "interface-aware" if width == 0 else "seeds"
    return {
        "ablate": "ablation",
        "sfloor": "seed floor",
        "floor": "floor (uniform)",
        **COMPARATOR_LABELS,
    }[mode]


def tabular(
    header: list[str], rows: list[list[str] | None], align: str, source: str
) -> str:
    """A booktabs fragment; a ``None`` row is a ``\\midrule``."""
    lines = [
        f"% GENERATED by scripts/paper_figures.py from {source} -- do not edit.",
        rf"\begin{{tabular}}{{{align}}}",
        r"\toprule",
        " & ".join(header) + r" \\",
        r"\midrule",
    ]
    for row in rows:
        lines.append(r"\midrule" if row is None else " & ".join(row) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


def _widths(cache: ResultsCache) -> list[float]:
    return sorted(w for w in cache.values("delta", "error") if w is not None)


def _ns(cache: ResultsCache) -> list[int]:
    return sorted({r["n"] for r in cache.select("error")})


def n_header(ns: list[int]) -> list[str]:
    return [f"$n = {ns[0]}$"] + [f"${n}$" for n in ns[1:]]


def table_1d(cache: ResultsCache, source: str) -> str:
    """Notes §2: relative error in f per edge width, standard FD4 and seeds."""
    ns = _ns(cache)
    rows: list[list[str] | None] = []
    for width in _widths(cache):
        for mode in ("naive", "aware"):
            recs = cache.select("error", delta=width, mode=mode, field="f")
            rows.append(
                [delta_label(width), mode_label(mode, width, one_d=True)]
                + [sci(r["error"]) for r in recs]
                + [rates_cell(recs)]
            )
    header = [r"$\delta$", "scheme", *n_header(ns), "rates"]
    return tabular(header, rows, "ll" + "r" * len(ns) + "l", source)


def table_1d_comparators(
    cache: ResultsCache,
    source: str,
    modes: tuple[str, ...] = ("naive", "cell", "cell2", "bandlimit", "aware"),
) -> str:
    """Notes §2.1 (#69): the standard scheme on the treated media against the
    standard scheme on the true one and the seeds, per edge width."""
    ns = _ns(cache)
    rows: list[list[str] | None] = []
    for width in _widths(cache):
        for mode in modes:
            recs = cache.select("error", delta=width, mode=mode, field="f")
            if not recs:
                continue
            rows.append(
                [delta_label(width), mode_label(mode, width, one_d=True)]
                + [sci(r["error"]) for r in recs]
                + [rates_cell(recs)]
            )
        rows.append(None)
    header = [r"$\delta$", "medium, scheme", *n_header(ns), "rates"]
    return tabular(header, rows[:-1], "ll" + "r" * len(ns) + "l", source)


def table_2d(
    cache: ResultsCache,
    field: str,
    source: str,
    *,
    rates: bool = True,
    widths: list[float] | None = None,
) -> str:
    """Notes §5.4–5.6: one field's error per (edge width, operator), the
    floor last. ``field`` is ``v``, ``h``, ``u`` or ``max_u``."""
    ns = _ns(cache)
    rows: list[list[str] | None] = []
    for width in widths if widths is not None else _widths(cache):
        modes = cache.values("mode", "error", delta=width, field=field)
        for mode in sorted(modes, key=MODE_ORDER.index):
            recs = cache.select("error", delta=width, mode=mode, field=field)
            row = [delta_label(width), mode_label(mode, width)]
            row += [sci(r["error"]) for r in recs]
            if rates:
                row.append(rates_cell(recs))
            rows.append(row)
    floor = cache.select("error", delta=None, mode="floor", field=field)
    if floor:
        rows.append(None)
        row = ["floor", "naive, uniform"] + [sci(r["error"]) for r in floor]
        if rates:
            row.append(rates_cell(floor))
        rows.append(row)
    header = [r"$\delta$", "operator", *n_header(ns)] + (["rates"] if rates else [])
    align = "ll" + "r" * len(ns) + ("l" if rates else "")
    return tabular(header, rows, align, source)


def table_truncation(cache: ResultsCache, source: str) -> str:
    """Notes §5.6: truncation error on the reference state, edge rows of the
    naive and seed operators against the bulk rows."""
    rows: list[list[str] | None] = []
    for width in sorted(w for w in cache.values("delta", "truncation")):
        for n in sorted({r["n"] for r in cache.select("truncation", delta=width)}):
            get = {
                (r["mode"], r["group"]): r["error"]
                for r in cache.select("truncation", delta=width, n=n)
            }
            bulk = get[("aware", "bulk")]
            rows.append(
                [
                    delta_label(width),
                    f"${n}$",
                    sci(get[("naive", "edge")]),
                    sci(get[("aware", "edge")]),
                    sci(bulk),
                    f"{get[('aware', 'edge')] / bulk:.1f}",
                ]
            )
    header = [
        r"$\delta$",
        "$n$",
        "naive, edge rows",
        "seeds, edge rows",
        "bulk rows",
        "seeds/bulk",
    ]
    return tabular(header, rows, "llrrrr", source)


def width_label_tex(label: str) -> str:
    if label in ("jump", "uniform"):
        return "jump" if label == "jump" else "(floor)"
    return "$h$" if label == "h/1" else f"${label}$"


def table_spectra(cache: ResultsCache, source: str) -> str:
    """Notes §5.3: the spectra summary, one row per (edge width, operator);
    the run columns appear when the cache has them."""
    recs = cache.select("spectrum")
    measured = [
        k
        for k in ("energy_ratio", "max_u", "err_v")
        if any(r[k] is not None for r in recs)
    ]
    # On the curved geometry the true u is not zero, so max |u| measures
    # nothing about the scheme; the notes leave that column out there too.
    if cache.args.get("amplitude", 0.0):
        measured = [k for k in measured if k != "max_u"]
    names = {
        "energy_ratio": "$E(1)/E(0)$",
        "max_u": r"max $|u|$",
        "err_v": "error in $v$",
    }
    rows: list[list[str] | None] = []
    for r in recs:
        row = [
            width_label_tex(r["width_label"]),
            VARIANT_LABELS.get(r["variant"], r["variant"]),
            f"${r['rows']}$",
            sci(r["max_re_hyper"]).replace(r"\sci{", r"\sci{+")
            if r["max_re_hyper"] > 0
            else sci(r["max_re_hyper"]),
            f"{r['rk4_max']:.5f}",
        ]
        for k in measured:
            v = r[k]
            row.append(
                "--" if v is None else (f"{v:.3f}" if k == "energy_ratio" else sci(v))
            )
        rows.append(row)
    header = [
        r"$\delta$",
        "operator",
        "rebuilt rows",
        r"max Re $\lambda$, with $\gamma$",
        r"RK4 max $|R|$",
    ]
    header += [names[k] for k in measured]
    return tabular(header, rows, "llrrr" + "r" * len(measured), source)


def write_fragment(path: Path, text: str) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    return path
