"""Table fragments of #54 on a synthetic cache: formatting and layout, no sweeps."""

import pytest

from pdes_demo.results_cache import ResultsCache
from pdes_demo.stiff_tables import (
    rates_cell,
    sci,
    table_1d,
    table_2d,
    table_spectra,
    table_truncation,
)


@pytest.mark.parametrize(
    "value, text",
    [
        (6.2e-8, r"\sci{6.2}{-8}"),
        (3.95e-3, r"\sci{4.0}{-3}"),
        (1.58e-2, r"\sci{1.58}{-2}"),  # a leading 1 gets the third digit
        (0.125, r"\sci{1.25}{-1}"),
        (9.96e-3, r"\sci{1.00}{-2}"),  # rounding up rolls the exponent
        (1.996e-3, r"\sci{2.0}{-3}"),  # ... and the leading-1 rule with it
        (-4.2e-2, r"\sci{-4.2}{-2}"),
        (0.0, "$0$"),
        (None, "--"),
    ],
)
def test_sci_formats_like_the_notes(value, text) -> None:
    assert sci(value) == text


def test_sci_honours_an_explicit_precision() -> None:
    assert sci(1.58e-2, sig=2) == r"\sci{1.6}{-2}"
    assert sci(6.25e-8, sig=3) == r"\sci{6.25}{-8}"


def _cache_2d(u_field: str = "max_u") -> ResultsCache:
    cache = ResultsCache.new("scripts/wave2d_stiff.py", {"amplitude": 0.0})
    ns = [2500, 4900]
    h = [n**-0.5 for n in ns]
    for delta, mode, v in [
        (0.0, "naive", [1.3e-1, 7.2e-2]),
        (0.0, "aware", [5.4e-2, 1.8e-2]),
        (0.0025, "naive", [8.9e-2, 4.8e-2]),
        (0.0025, "aware", [3.0e-2, 7.7e-3]),
        (0.0025, "sfloor", [2.7e-2, 6.7e-3]),
    ]:
        cache.add_errors(ns, v, [1.7], h=h, delta=delta, mode=mode, field="v")
        cache.add_errors(ns, v, [1.7], h=h, delta=delta, mode=mode, field=u_field)
    cache.add_errors(
        ns, [5.2e-2, 1.8e-2], [3.0], h=h, delta=None, mode="floor", field="v"
    )
    return cache


def test_table_1d_has_one_row_per_width_and_scheme() -> None:
    cache = ResultsCache.new("scripts/wave1d_stiff.py", {})
    ns = [100, 200, 400]
    h = [2 / n for n in ns]
    for delta in (0.0, 0.0025):
        for mode, e in (
            ("naive", [7e-2, 3e-2, 1.6e-2]),
            ("aware", [4e-3, 2.5e-4, 1.6e-5]),
        ):
            cache.add_errors(ns, e, [1.2, 1.0], h=h, delta=delta, mode=mode, field="f")
    text = table_1d(cache, "paper/data/x.json")
    lines = text.splitlines()
    assert lines[0].startswith(
        "% GENERATED by scripts/paper_figures.py from paper/data/x.json"
    )
    assert r"\begin{tabular}{lllrrrl}" not in text  # two label columns, three n, rates
    assert r"\begin{tabular}{llrrrl}" in text
    assert r"$n = 100$ & $200$ & $400$ & rates \\" in text
    body = [ln for ln in lines if ln.endswith(r"\\")][1:]
    assert len(body) == 4
    assert body[0].startswith(r"$0$ (jump) & standard FD4 & \sci{7.0}{-2}")
    assert body[1].startswith(r"$0$ (jump) & interface-aware")
    assert body[3].startswith(r"$0.0025$ & seeds")
    assert body[3].endswith(r"& 1.2, 1.0 \\")


def test_table_2d_orders_modes_and_puts_the_floor_last() -> None:
    cache = _cache_2d()
    text = table_2d(cache, "v", "src.json")
    body = [ln for ln in text.splitlines() if ln.endswith(r"\\")][1:]
    labels = [" & ".join(ln.split(" & ")[:2]) for ln in body]
    assert labels == [
        "$0$ (jump) & naive",
        "$0$ (jump) & interface-aware",
        "$0.0025$ & naive",
        "$0.0025$ & seeds",
        "$0.0025$ & seed floor",
        "floor & naive, uniform",
    ]
    assert text.count(r"\midrule") == 2  # header rule and the one before the floor
    # no rates column when asked, and the max_u field (no floor record) no floor row
    no_rates = table_2d(cache, "max_u", "src.json", rates=False)
    header = [ln for ln in no_rates.splitlines() if ln.endswith(r"\\")][0]
    assert header == r"$\delta$ & operator & $n = 2500$ & $4900$ \\"
    assert not any(ln.startswith("floor &") for ln in no_rates.splitlines())
    assert r"\begin{tabular}{llrr}" in no_rates


def test_table_2d_restricts_to_the_widths_asked() -> None:
    text = table_2d(_cache_2d(), "v", "src.json", widths=[0.0025])
    assert "(jump)" not in text and "$0.0025$" in text


def test_rates_cell_skips_the_first_resolution() -> None:
    recs = [{"rate": None}, {"rate": 3.96}, {"rate": 4.04}]
    assert rates_cell(recs) == "4.0, 4.0"


def test_table_truncation_computes_the_seed_to_bulk_ratio() -> None:
    cache = ResultsCache.new("scripts/wave2d_stiff.py", {})
    for mode, group, err in [
        ("naive", "edge", 3.9e-2),
        ("naive", "bulk", 2.5e-3),
        ("aware", "edge", 9.0e-3),
        ("aware", "bulk", 2.5e-3),
    ]:
        cache.add(
            "truncation", n=2500, h=0.02, delta=0.005, mode=mode, group=group, error=err
        )
    text = table_truncation(cache, "src.json")
    row = [ln for ln in text.splitlines() if ln.startswith("$0.005$")][0]
    assert (
        row
        == r"$0.005$ & $2500$ & \sci{3.9}{-2} & \sci{9.0}{-3} & \sci{2.5}{-3} & 3.6 \\"
    )


def test_table_spectra_adds_run_columns_only_when_measured() -> None:
    cache = ResultsCache.new("scripts/wave2d_stiff_eigenvalues.py", {})
    common = dict(
        n=2500, h=0.02, dt=0.004, gamma=2.4e-11, max_re=40.0, min_re_hyper=-200.0
    )
    cache.add(
        "spectrum",
        delta=0.0,
        width_label="jump",
        variant="naive",
        rows=0,
        max_re_hyper=3.5e-3,
        rk4_max=1.00001,
        **common,
    )
    text = table_spectra(cache, "src.json")
    assert "$E(1)/E(0)$" not in text
    assert r"jump & naive & $0$ & \sci{+3.5}{-3} & 1.00001 \\" in text
    cache.add(
        "spectrum",
        delta=0.0025,
        width_label="h/8",
        variant="seeds",
        rows=985,
        max_re_hyper=6.3e-2,
        rk4_max=1.0003,
        energy_ratio=0.995,
        max_u=1.7e-3,
        err_v=3.0e-2,
        **common,
    )
    text = table_spectra(cache, "src.json")
    assert "$E(1)/E(0)$" in text and r"max $|u|$" in text
    row = r"$h/8$ & seeds & $985$ & \sci{+6.3}{-2} & 1.00030 & 0.995 & "
    assert row + r"\sci{1.70}{-3} & \sci{3.0}{-2} \\" in text
    assert r"jump & naive & $0$ & \sci{+3.5}{-3} & 1.00001 & -- & -- & -- \\" in text
